const db  = require('./index');

// {
//   "id":"abc123", #this should be automatically generated by your API and should probably be a string
//   "name": "Sea Witch", #The name of the boat, a string
//   "type":"Catamaran", #The type of boat, power boat, sailboat, catamaran etc. a string
//   "length":28, #The length of the boat
//   "at_sea":false #A boolean indicating if the boat is at sea or not
// }

const KIND = 'boat';


async function getAllBoats() {
  try {
    const query = db.createQuery(KIND);

    const response = await query.run();

    const boats = response[0].map( (boat) => {
      boat.id = boat[db.KEY].id;
      return boat;
    });

    return boats;
  } catch (error) {
    throw error;
  }
}


async function createBoat({ name, type, length }) {
  try {
    const key = db.key(KIND);
    const boat = {
      key,
      data: {
        name,
        type,
        length,
        at_sea: false
      }
    };

    await db.save(boat);

    return key.path[1];
  } catch (error) {
    throw error;
  }
}

async function getBoat({ id }){
  try {
    const key       = await db.key([KIND, id]);
    const response  = await db.get(key);

    const boat = response[0];

    if( boat ){
      boat.id = boat[db.KEY].id;
      return boat;
    } else {
      return null;
    }
  } catch (error) {
    throw error;
  }
}

module.exports = {
  getAllBoats,
  createBoat,
  getBoat
}
