const db  = require('./index');


// {
//   "id":"123abc", #A string generated by your API
//   "number": 5, #The the slip number, essentially the human understandable identifier
//   "current_boat":"abc555",  #The id of the current boat, null if empty
//   "arrival_date":"1/1/2015", #A string indicating the date the boat arrived in the slip
//   "departure_history":[{"departure_date":"11/4/2014","departed_boat":"123aaa"}...] #Optional for 5% extra credit a list of the dates that previous boats departed the slip
// }

const KIND = 'slip';
