const db  = require('./index');


// {
//   "id":"123abc", #A string generated by your API
//   "number": 5, #The the slip number, essentially the human understandable identifier
//   "current_boat":"abc555",  #The id of the current boat, null if empty
//   "arrival_date":"1/1/2015", #A string indicating the date the boat arrived in the slip
//   "departure_history":[{"departure_date":"11/4/2014","departed_boat":"123aaa"}...] #Optional for 5% extra credit a list of the dates that previous boats departed the slip
// }

const KIND = 'slip';


async function getAllSlips() {
  try {
    return await db.getAllOfKind(KIND);
  } catch (error) {
    throw error;
  }
}


async function createSlip({ number }) {
  try {
    const data = {
      number,
      current_boat: '',
      arrival_date: '',
      departure_history: []
    };

    return await db.createEntity({ KIND, data });
  } catch (error) {
    throw error;
  }
}


async function getSlip({ id }){
  try {
    return await db.getEntityById({ KIND, id });
  } catch (error) {
    throw error;
  }
}


async function updateSlip({ id, number, current_boat, arrival_date, departure_history }) {
  try {
    const data = {
        number,
        current_boat,
        arrival_date,
        departure_history
    };

    return await db.updateEntity({ KIND, id, data });
  } catch (error) {
    throw error;
  }
}


async function deleteSlip({ id }) {
  try {
    return await db.deleteEntity({ KIND, id });
  } catch (error) {
    throw error;
  }
}


module.exports = {
  getAllSlips,
  createSlip,
  getSlip,
  updateSlip,
  deleteSlip
}
